GET http://localhost:8080/shorten/e5e5

###

POST /shorten HTTP/1.1
Content-Type: application/json
Host: localhost:8080

{
    "url": "www.qwaaazxce.com"
}

###

PUT /shorten/e5e5 HTTP/1.1
Content-Type: application/json
Host: localhost:8080

{
    "url": "www.omgaAfddd.com"
}

###

DELETE /shorten/e5e5 HTTP/1.1
Content-Type: application/json
Host: localhost:8080